# Default values for monster-rolodex.
replicaCount: 1

image:
  repository: ghcr.io/rratillajr/rratillajr/monster-rolodex
  tag: development ##
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  }
  path: /
  hosts:
    - dev.monster-rolodex.local ##
  tls: []

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
