apiVersion: v1
kind: Service
metadata:
  name: {{ template "monster-rolodex.fullname" . }}
  labels:
    app: {{ template "monster-rolodex.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ template "monster-rolodex.name" . }}
