# Default values for monster-rolodex.
replicaCount: 1

image:
  repository: ghcr.io/rratillajr/rratillajr/monster-rolodex
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - monster-rolodex.local

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
