name: Deploy to Development

on:
  repository_dispatch:
    types:
      - deploy-to-dev
  workflow_dispatch:
  
env:
  VALUES_YAML: dev-values.yaml
  TAG: x

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          
      - name: Set tag
        run:
          echo "TAG=$(awk '/tag:/ {print $2}' $env.VALUES_YAML)"
          
      - uses: azure/setup-helm@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        id: install
          
      - name: Set image if coming from dispatch
        if: ${{ github.event.client_payload.imageTag }}
        run: echo ${{ env.TAG }}
        env:
          TAG: ${{ github.event.client_payload.imageTag }}

      - name: Run Helm template
        run: |
          rm -rf dev
          sed -i "/tag:/ c\  tag: ${{ env.TAG }}" ${{ env.VALUES_YAML }}
          cat ${{ env.VALUES_YAML }} | grep tag
          helm template monster-rolodex-dev . -f ${{ env.VALUES_YAML }} --output-dir dev
          
      - name: Auto-commit back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "New app image tag: ${{ env.TAG }}"
