name: Deploy to Development

on:
  repository_dispatch:
    types:
      - deploy-to-dev
  workflow_dispatch:

env:
  TAG: ${{ github.ref_name }}
  

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - uses: azure/setup-helm@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        id: install
          
      - name: Set image if coming from dispatch
        if: ${{ github.event.client_payload.imageTag }}
        env:
          TAG: ${{ github.event.client_payload.imageTag }}

      - name: Run Helm template
        run: |
          export valuesyaml="dev-values.yaml"
          rm -rf dev
          sed -i "s|$(awk '/tag:/ {print $2}' $valuesyaml | cut -d: -f2)|${{ env.TAG }}|g" $valuesyaml
          helm template monster-rolodex-dev . -f $valuesyaml --output-dir dev
          
      - name: Auto-commit back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "New app image tag: ${{ env.TAG }}"
