name: Helm Template

on:
  workflow_dispatch:
  # repository_dispatch:
  #   types:
  #     - patch-app-image-tag # Event type defined in the triggering workflow

jobs:
  helm_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v2
        with:
          version: 'v3'

      - name: Run Helm template
        run: |
          sed -i 's|${grep -o 'tag:[^ ]*' values.yaml | cut -d ':' -f 2}|${{ github.event.client_payload.imageTag }}|g' values.yaml
          helm template monster-rolodex . --output-dir .

