name: Helm Template

on:
  # workflow_dispatch:
   repository_dispatch:
     types:
       - patch-app-image-tag

jobs:
  helm_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Run Helm template
        run: |
          echo ${{ github.event.client_payload.imageTag }}
          sed -i "s|$(awk '/tag:/ {print $2}' values.yaml | cut -d: -f2)|${{ github.event.client_payload.imageTag }}|g" values.yaml
          cat values.yaml
          helm template monster-rolodex . --output-dir .

