name: Manual Dispatch

on:
   workflow_dispatch:

jobs:
  helm_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - uses: azure/setup-helm@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Run Helm template
        run: |
          rm -rf monster-rolodex
          helm template monster-rolodex . --output-dir .
      
      - name: Auto-commit back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
