name: Helm Template

on:
   workflow_dispatch:

jobs:
  helm_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/setup-helm@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Run Helm template
        run: |
          rm -rf monster-rolodex/*
          helm template monster-rolodex . --output-dir .
