name: Helm Template

on:
   repository_dispatch:
     types:
       - patch-app-image-tag

jobs:
  helm_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - uses: azure/setup-helm@v3
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Run Helm template
        run: |
          rm -rf monster-rolodex/*
          sed -i "s|$(awk '/tag:/ {print $2}' values.yaml | cut -d: -f2)|${{ github.event.client_payload.imageTag }}|g" values.yaml
          helm template monster-rolodex . --output-dir .
          
      - name: Auto-commit back to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "New app image tag: ${{ github.event.client_payload.imageTag }}"
